### ISSUE TITLE
Error on generating config in latest update

### ISSUE THREAD

**Issue by sluhtie** [DiSkyOrg/DiSky#120]
I removed the old Disky folder such as the old .jar file and each time I start the server a new folder does get generated but I get an exception on generating the config.

This only occurs if no previous config file does not exist!
The Error:
```[15:47:02 ERROR]: Cannot load plugins/DiSky/config.yml
java.io.FileNotFoundException: plugins/DiSky/config.yml (No such file or directory)
        at java.io.FileInputStream.open0(Native Method) ~[?:?]
        at java.io.FileInputStream.open(FileInputStream.java:216) ~[?:?]
        at java.io.FileInputStream.<init>(FileInputStream.java:157) ~[?:?]
        at org.bukkit.configuration.file.FileConfiguration.load(FileConfiguration.java:126) ~[paper-api-1.19.3-R0.1-SNAPSHOT.jar:?]
        at info.itsthesky.disky.managers.Configuration.loadConfiguration(Configuration.java:41) ~[DiSky 4.11.0.jar:?]
        at info.itsthesky.disky.DiSky.onEnable(DiSky.java:69) ~[DiSky 4.11.0.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:279) ~[paper-api-1.19.3-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:192) ~[paper-1.19.3.jar:git-Paper-445]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104) ~[paper-1.19.3.jar:git-Paper-445]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507) ~[paper-api-1.19.3-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_19_R2.CraftServer.enablePlugin(CraftServer.java:560) ~[paper-1.19.3.jar:git-Paper-445]
        at org.bukkit.craftbukkit.v1_19_R2.CraftServer.enablePlugins(CraftServer.java:471) ~[paper-1.19.3.jar:git-Paper-445]
        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:635) ~[paper-1.19.3.jar:git-Paper-445]
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:434) ~[paper-1.19.3.jar:git-Paper-445]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:308) ~[paper-1.19.3.jar:git-Paper-445]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1101) ~[paper-1.19.3.jar:git-Paper-445]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:316) ~[paper-1.19.3.jar:git-Paper-445]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]```

**Comment by SkyCraft78** [comment]
It's gonna be fixed in the next version. Thanks for the reports!
