### ISSUE TITLE
paper 1.20.2

### ISSUE THREAD

**Issue by HopeJ-Personal** [DiSkyOrg/DiSky#169]
I know the latest version is for 1.20.1 and was hoping id get lucky and it work for 1.20.2 it does not. I can give my logs her but also is there any plans to update to 1.20.2 because I cant find any discord API addon with bots for skript that work, I found one for webhooks but I need a bot that can read previous messages send embeds and messages like this one.

**Edit:** oh and here's the log with this and likely more helpful information in it :D 
[latest.log](https://github.com/DiSkyOrg/DiSky/files/14621772/latest.log)

~~~
[17:22:51 INFO]: [DiSky] Enabling DiSky v4.12.0
[17:22:51 INFO]: [DiSky] Loading emoji library ...
[17:22:51 INFO]: [DiSky] Success!
[17:22:51 WARN]: java.lang.NoSuchMethodException: ch.njol.skript.lang.SkriptParser.parse_i(java.lang.String,int,int)
[17:22:51 WARN]:        at java.base/java.lang.Class.getDeclaredMethod(Class.java:2848)
[17:22:51 WARN]:        at DiSky 4.12.0.jar//info.itsthesky.disky.elements.commands.CommandFactory.<init>(CommandFactory.java:42)
[17:22:51 WARN]:        at DiSky 4.12.0.jar//info.itsthesky.disky.elements.commands.CommandFactory.<clinit>(CommandFactory.java:28)
[17:22:51 WARN]:        at java.base/java.lang.Class.forName0(Native Method)
[17:22:51 WARN]:        at java.base/java.lang.Class.forName(Class.java:534)
[17:22:51 WARN]:        at java.base/java.lang.Class.forName(Class.java:513)
[17:22:51 WARN]:        at Skript.jar//ch.njol.skript.util.Utils.getClasses(Utils.java:201)
[17:22:51 WARN]:        at Skript.jar//ch.njol.skript.SkriptAddon.loadClasses(SkriptAddon.java:82)
[17:22:51 WARN]:        at DiSky 4.12.0.jar//info.itsthesky.disky.DiSky.onEnable(DiSky.java:123)
[17:22:51 WARN]:        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:281)
[17:22:51 WARN]:        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:190)
[17:22:51 WARN]:        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104)
[17:22:51 WARN]:        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507)
[17:22:51 WARN]:        at org.bukkit.craftbukkit.v1_20_R2.CraftServer.enablePlugin(CraftServer.java:646)
[17:22:51 WARN]:        at org.bukkit.craftbukkit.v1_20_R2.CraftServer.enablePlugins(CraftServer.java:557)
[17:22:51 WARN]:        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:627)
[17:22:51 WARN]:        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:424)
[17:22:51 WARN]:        at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:308)
[17:22:51 WARN]:        at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1086)
[17:22:51 WARN]:        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:315)
[17:22:51 WARN]:        at java.base/java.lang.Thread.run(Thread.java:1583)
[17:22:51 INFO]: [Skript]     Skript's 'parse_i' method could not be resolved.
[17:22:52 ERROR]: Error occurred while enabling DiSky v4.12.0 (Is it up to date?)
java.lang.NoSuchFieldError: Class ch.njol.skript.lang.ExpressionInfo does not have member field 'java.lang.Class c'
        at info.itsthesky.disky.api.ReflectionUtils.lambda$removeElement$0(ReflectionUtils.java:255) ~[DiSky 4.12.0.jar:?]
        at java.util.ArrayList.removeIf(ArrayList.java:1755) ~[?:?]
        at java.util.ArrayList.removeIf(ArrayList.java:1743) ~[?:?]
        at info.itsthesky.disky.api.ReflectionUtils.removeElement(ReflectionUtils.java:255) ~[DiSky 4.12.0.jar:?]
        at info.itsthesky.disky.elements.properties.PermissionsOf.<clinit>(PermissionsOf.java:41) ~[DiSky 4.12.0.jar:?]
        at java.lang.Class.forName0(Native Method) ~[?:?]
        at java.lang.Class.forName(Class.java:534) ~[?:?]
        at java.lang.Class.forName(Class.java:513) ~[?:?]
        at ch.njol.skript.util.Utils.getClasses(Utils.java:201) ~[Skript.jar:?]
        at ch.njol.skript.SkriptAddon.loadClasses(SkriptAddon.java:82) ~[Skript.jar:?]
        at info.itsthesky.disky.DiSky.onEnable(DiSky.java:123) ~[DiSky 4.12.0.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:281) ~[paper-api-1.20.2-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:190) ~[paper-1.20.2.jar:git-Paper-318]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104) ~[paper-1.20.2.jar:git-Paper-318]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507) ~[paper-api-1.20.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_20_R2.CraftServer.enablePlugin(CraftServer.java:646) ~[paper-1.20.2.jar:git-Paper-318]
        at org.bukkit.craftbukkit.v1_20_R2.CraftServer.enablePlugins(CraftServer.java:557) ~[paper-1.20.2.jar:git-Paper-318]
        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:627) ~[paper-1.20.2.jar:git-Paper-318]
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:424) ~[paper-1.20.2.jar:git-Paper-318]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:308) ~[paper-1.20.2.jar:git-Paper-318]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1086) ~[paper-1.20.2.jar:git-Paper-318]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:315) ~[paper-1.20.2.jar:git-Paper-318]
        at java.lang.Thread.run(Thread.java:1583) ~[?:?]
[17:22:52 INFO]: [DiSky] Disabling DiSky v4.12.0
~~~

**Comment by EquipableMC** [comment]
Skript version? Disky works for 1.20+

**Comment by ItsTheSky** [comment]
Either update Disky to v4.12.2 or downgrade your Skript version.
