### ISSUE TITLE
unregister command throws error

### ISSUE THREAD

**Issue by EquipableMC** [DiSkyOrg/DiSky#171]
[03:17:27 ERROR]: [net.dv8tion.jda.api.requests.RestAction] Encountered error while processing success consumer
java.lang.IllegalArgumentException: RestActions may not be empty
        at net.dv8tion.jda.internal.utils.Checks.notEmpty(Checks.java:115) ~[DiSky 4.12.2-beta1.jar:?]
        at net.dv8tion.jda.api.requests.RestAction.accumulate(RestAction.java:359) ~[DiSky 4.12.2-beta1.jar:?]
        at net.dv8tion.jda.api.requests.RestAction.allOf(RestAction.java:325) ~[DiSky 4.12.2-beta1.jar:?]
        at info.itsthesky.disky.elements.components.commands.UnregisterCommand.lambda$runEffect$4(UnregisterCommand.java:73) ~[DiSky 4.12.2-beta1.jar:?]
        at net.dv8tion.jda.api.requests.Request.lambda$onSuccess$0(Request.java:123) ~[DiSky 4.12.2-beta1.jar:?]
        at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1395) ~[?:?]
        at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) ~[?:?]
        at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) ~[?:?]
        at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) ~[?:?]
        at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) ~[?:?]
        at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) ~[?:?]

**Comment by EquipableMC** [comment]
this happens when I try to unregister a command that disky thinks doesn't exist but does

**Comment by EquipableMC** [comment]
![image](https://github.com/DiSkyOrg/DiSky/assets/66171067/305859ea-b5ee-4ba2-9296-fb520321d0c0)

**Comment by EquipableMC** [comment]
then it registers twice

**Comment by EquipableMC** [comment]
Nevermind, disky is just weird
