### ISSUE TITLE
Discord commands do not work

### ISSUE THREAD

**Issue by EdouxDev** [DiSkyOrg/DiSky#204]
## Versions

- DiSky: `v4.16.0`
- Skript: `v2.7.3`
- Spigot/Paper: `v1.20.4 (Pufferfish)`

## Description
The code i used:
```
discord command ping:
    prefixes: !
    trigger:
        reply with "Pong!"
```
This code is same with the code in wiki.
There is no problem at reloading skript, it does not give me an error.
But when i go to my discord channel and type "!ping", it occurs an error(or warning) in console, and the "reply with Pong!" does not work.

![Ekran görüntüsü 2024-05-10 220651](https://github.com/DiSkyOrg/DiSky/assets/109683349/270f4e5a-dedc-4418-a37c-32a726572b56)
![Ekran görüntüsü 2024-05-10 220731](https://github.com/DiSkyOrg/DiSky/assets/109683349/52e7b74b-a0c9-4ae5-a4b8-a66f31df7eb0)

```
[DiSky] Task #3064 for DiSky v4.16.0 generated an exception
java.lang.NullPointerException: Cannot invoke "java.lang.reflect.Method.invoke(Object, Object[])" because "this.PARSE_I" is null
	at info.itsthesky.disky.elements.commands.CommandFactory.parseArguments(CommandFactory.java:64) ~[DiSky.4.16.0.jar:?]
	at info.itsthesky.disky.elements.commands.CommandObject.execute(CommandObject.java:68) ~[DiSky.4.16.0.jar:?]
	at info.itsthesky.disky.elements.commands.CommandListener.lambda$exe$0(CommandListener.java:91) ~[DiSky.4.16.0.jar:?]
	at org.bukkit.craftbukkit.v1_20_R3.scheduler.CraftTask.run(CraftTask.java:101) ~[pufferfish-1.20.4.jar:git-Pufferfish-47]
	at org.bukkit.craftbukkit.v1_20_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:482) ~[pufferfish-1.20.4.jar:git-Pufferfish-47]
	at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1653) ~[pufferfish-1.20.4.jar:git-Pufferfish-47]
	at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:450) ~[pufferfish-1.20.4.jar:git-Pufferfish-47]
	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1532) ~[pufferfish-1.20.4.jar:git-Pufferfish-47]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1227) ~[pufferfish-1.20.4.jar:git-Pufferfish-47]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:320) ~[pufferfish-1.20.4.jar:git-Pufferfish-47]
	at java.lang.Thread.run(Thread.java:1623) ~[?:?]
```

## Acknowledgment

- [ ] I have **read** the error correctly, and I'm **sure** it's directly a DiSky problem.
- [ ] I have **searched** for **similar** bugs on the [**Issues tab**](https://github.com/DiSkyOrg/DiSky/issues)

**Comment by TrasonCo** [comment]
This is no Disky error, your Skript versiojn is just too low you need 2.8+ (2.8.4 or 2.8.5 works too)

**Comment by EdouxDev** [comment]
Yeah i updated Skript and it is now working, sorry then it's my bad (requirements say that 2.6 is enough)
![image](https://github.com/DiSkyOrg/DiSky/assets/109683349/b308144f-3118-4efc-9f34-2615ee208a96)

**Comment by EquipableMC** [comment]
> Yeah i updated Skript and it is now working, sorry then it's my bad (requirements say that 2.6 is enough) ![image](https://private-user-images.githubusercontent.com/109683349/329722065-b308144f-3118-4efc-9f34-2615ee208a96.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUzNzg5NzYsIm5iZiI6MTcxNTM3ODY3NiwicGF0aCI6Ii8xMDk2ODMzNDkvMzI5NzIyMDY1LWIzMDgxNDRmLTMxMTgtNGVmYy05ZjM0LTI2MTVlZTIwOGE5Ni5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTEwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUxMFQyMjA0MzZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wYzZhMDZlYmQwYmI3NGQ0YTgzMGZjZjg5MzQ0MjJiNTQ2ZTY3MjYzZjU3OTJkMTM2ZjI4ZTMzNzk1MzdhNTFkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.bUAc9NIyK5yg7lovrgfCsdPFt_ZA33sYRYn7GpBXSxs)

well yeah thats because there is older versions of Disky that work on 2.7.3 and below
