### ISSUE TITLE
CommandFactory lack of null check

### ISSUE THREAD

**Issue by kiip1** [DiSkyOrg/DiSky#220]
## Versions

- DiSky: `v4.17.3`
- Skript: `v2.8.4`
- Purpur: `v1.20.4`

## Description

Commit [f235dc8](https://github.com/DiSkyOrg/DiSky/commit/f235dc88e99d7b5b98118f2950fae0be5dd6fe99) "unfixed" the case where res == null would just return false.

```
NullPointerException: Cannot read field "exprs" because "res" is null
    at info.itsthesky.disky.elements.commands.CommandFactory.parseArguments(CommandFactory.java:120)
    at info.itsthesky.disky.elements.commands.CommandObject.execute(CommandObject.java:68)
    at info.itsthesky.disky.elements.commands.CommandListener.lambda$exe$0(CommandListener.java:102)
    at org.bukkit.craftbukkit.v1_20_R3.scheduler.CraftTask.run(CraftTask.java:101)
    at org.bukkit.craftbukkit.v1_20_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:482)
...
```
Exact case when it happens is unknown.

## Acknowledgment

- [x] I have **read** the error correctly, and I'm **sure** it's directly a DiSky problem.
- [x] I have **searched** for **similar** bugs on the [**Issues tab**](https://github.com/DiSkyOrg/DiSky/issues)

**Comment by EquipableMC** [comment]
Does this happen with 4.18?

**Comment by ItsTheSky** [comment]
"Fixed" (simply added a null check).
I Removed the part where DiSky tried to look over Discord types to parse arguments, because most of them require an async operation to have their values, while Discord commands were not designed to be async at all.
Thanks for the report :)
