### ISSUE TITLE
On member left guild event doesn't work

### ISSUE THREAD

**Issue by Vulqa** [DiSkyOrg/DiSky#28]
Hello,
When i use the "On member left guild" event i get an error in the console, and the script doesn't work correctly. I use DiSky 4.0-beta2

My code:
```
on member left guild seen by "BOT":
  post message "> %event-member% left the server!" in channel with id "{@logs_discord_channel}"
```

The error:
```
[19:52:04] [Server thread/WARN]: java.lang.NoSuchMethodException: info.itsthesky.disky.elements.events.member.MemberRemoveEvent$BukkitMemberRemoveEvent.<init>(info.itsthesky.disky.elements.events.member.MemberRemoveEvent)
[19:52:04] [Server thread/WARN]:        at java.base/java.lang.Class.getConstructor0(Class.java:3517)
[19:52:04] [Server thread/WARN]:        at java.base/java.lang.Class.getDeclaredConstructor(Class.java:2691)
[19:52:04] [Server thread/WARN]:        at info.itsthesky.disky.api.events.DiSkyEvent.init(DiSkyEvent.java:97)
[19:52:04] [Server thread/WARN]:        at ch.njol.skript.lang.SkriptParser.parseEvent(SkriptParser.java:1101)
[19:52:04] [Server thread/WARN]:        at ch.njol.skript.lang.SkriptParser.parseEvent(SkriptParser.java:1067)
[19:52:04] [Server thread/WARN]:        at ch.njol.skript.ScriptLoader.loadScript(ScriptLoader.java:739)
[19:52:04] [Server thread/WARN]:        at ch.njol.skript.ScriptLoader.lambda$loadScripts$4(ScriptLoader.java:525)
[19:52:04] [Server thread/WARN]:        at ch.njol.skript.ScriptLoader.lambda$makeFuture$2(ScriptLoader.java:417)
[19:52:04] [Server thread/WARN]:        at ch.njol.skript.ScriptLoader.makeFuture(ScriptLoader.java:433)
[19:52:04] [Server thread/WARN]:        at ch.njol.skript.ScriptLoader.loadScripts(ScriptLoader.java:524)
[19:52:04] [JDA MainWS-ReadThread/INFO]: Connected to WebSocket
[19:52:04] [Server thread/WARN]:        at ch.njol.skript.ScriptLoader.reloadScript(ScriptLoader.java:1060)
[19:52:04] [Server thread/WARN]:        at ch.njol.skript.SkriptCommand.onCommand(SkriptCommand.java:171)
[19:52:04] [Server thread/WARN]:        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45)
[19:52:04] [Server thread/WARN]:        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:145)
[19:52:04] [Server thread/WARN]:        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.dispatchCommand(CraftServer.java:732)
[19:52:04] [Server thread/WARN]:        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.dispatchServerCommand(CraftServer.java:717)
[19:52:04] [Server thread/WARN]:        at net.minecraft.server.v1_16_R3.DedicatedServer.handleCommandQueue(DedicatedServer.java:411)
[19:52:04] [Server thread/WARN]:        at net.minecraft.server.v1_16_R3.DedicatedServer.b(DedicatedServer.java:380)
[19:52:04] [Server thread/WARN]:        at net.minecraft.server.v1_16_R3.MinecraftServer.a(MinecraftServer.java:1071)
[19:52:04] [Server thread/WARN]:        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:910)
[19:52:04] [Server thread/WARN]:        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$0(MinecraftServer.java:256)
[19:52:04] [Server thread/WARN]:        at java.base/java.lang.Thread.run(Thread.java:831)
```

**Comment by wallace4BR** [comment]
@Vulqa can you please test with this build?
https://github.com/DiSkyOrg/DiSky/actions/runs/2246457856

**Comment by SkyCraft78** [comment]
Wallace made the right changes to fix your problem.
You can either wait for a real release of DiSky, or use the action Wallace mentioned in it's previous message.
Feel free to re-open this issue if the problem is still heren😄

**Comment by Vulqa** [comment]
> @Vulqa can you please test with this build? https://github.com/DiSkyOrg/DiSky/actions/runs/2246457856

Sorry for reopening this issue, but the build of @wallace4BR doesn't work, i put the logs of the console below. Thanks for the help, i will wait for the next update no problem 🙂 

```
§c    Can't understand this event: 'define new bot named "Communauté Epicube"'
§6    Line: §7define new bot named "Communauté Epicube":
 §r
[09:54:49] [Server thread/ERROR]: [Skript] §c§lLine 22:§7 (bot.sk)
§c    Can't understand this event: 'on ready'
§6    Line: §7on ready:
 §r
[09:54:49] [Server thread/ERROR]: [Skript] §c§lLine 27:§7 (bot.sk)
§c    Can't compare a text with 'loaded in discord'
§6    Line: §7if "Communauté Epicube" is loaded in discord:
 §r
[09:54:49] [Server thread/ERROR]: [Skript] §c§lLine 32:§7 (bot.sk)
§c    Can't understand this event: 'on message receive seen by "Communauté Epicube"'
§6    Line: §7on message receive seen by "Communauté Epicube":
 §r
[09:54:49] [Server thread/ERROR]: [Skript] §c§lLine 45:§7 (bot.sk)
§c    Can't understand this event: 'on member join guild seen by "Communauté Epicube"'
§6    Line: §7on member join guild seen by "Communauté Epicube":
 §r
[09:54:49] [Server thread/ERROR]: [Skript] §c§lLine 48:§7 (bot.sk)
§c    Can't understand this event: 'on member left guild seen by "Communauté Epicube"'
§6    Line: §7on member left guild seen by "Communauté Epicube":
 §r
[09:54:49] [Server thread/ERROR]: [Skript] §c§lLine 53:§7 (bot.sk)
§c    Can't understand this event: 'on guild ready'
§6    Line: §7on guild ready:
 §r
[09:54:49] [Server thread/ERROR]: [Skript] §c§lLine 62:§7 (bot.sk)
§c    Can't understand this event: 'on slash command'
§6    Line: §7on slash command:
```

**Comment by SkyCraft78** [comment]
Are you sure DiSky is been loaded here? 
Do `/disky debug` and send a screenshot here please.

**Comment by Vulqa** [comment]
> Are you sure DiSky is been loaded here? Do `/disky debug` and send a screenshot here please.

The command `/disky debug` returns nothing

```
[13:09:07] [Server thread/ERROR]: [Skript] §c§lLine 28:§7 (bot.sk)
§c    Can't compare a text with 'loaded in discord'
§6    Line: §7if "Communauté Epicube" is loaded in discord:
 §r
[13:09:07] [Server thread/ERROR]: [Skript] §c§lLine 33:§7 (bot.sk)
§c    Can't understand this event: 'on message receive seen by "Communauté Epicube"'
§6    Line: §7on message receive seen by "Communauté Epicube":
 §r
[13:09:07] [Server thread/ERROR]: [Skript] §c§lLine 46:§7 (bot.sk)
§c    Can't understand this event: 'on member join guild seen by "Communauté Epicube"'
§6    Line: §7on member join guild seen by "Communauté Epicube":
 §r
[13:09:07] [Server thread/ERROR]: [Skript] §c§lLine 49:§7 (bot.sk)
§c    Can't understand this event: 'on member left guild seen by "Communauté Epicube"'
§6    Line: §7on member left guild seen by "Communauté Epicube":
 §r
[13:09:07] [Server thread/ERROR]: [Skript] §c§lLine 54:§7 (bot.sk)
§c    Can't understand this event: 'on guild ready'
§6    Line: §7on guild ready:
 §r
[13:09:07] [Server thread/ERROR]: [Skript] §c§lLine 63:§7 (bot.sk)
§c    Can't understand this event: 'on slash command'
§6    Line: §7on slash command:
 §r
[13:09:07] [Server thread/INFO]: [Skript] Loaded 1 script with a total of 1 trigger and 0 commands in 0.1 seconds
[13:09:07] [Server thread/INFO]: [Skript] Finished loading.
>disky debug
>about DiSky
[13:09:27] [Server thread/INFO]: DiSky version 4.0-beta2
[13:09:27] [Server thread/INFO]: The new generation of DiSky, even more powerful and complete!
[13:09:27] [Server thread/INFO]: Author: ItsTheSky
>pl
[13:09:29] [Server thread/INFO]: Plugins (2): Skript, DiSky
```

**Comment by wallace4BR** [comment]
> > Are you sure DiSky is been loaded here? Do `/disky debug` and send a screenshot here please.
> 
> The command `/disky debug` returns nothing
> 
> ```
> [13:09:07] [Server thread/ERROR]: [Skript] §c§lLine 28:§7 (bot.sk)
> §c    Can't compare a text with 'loaded in discord'
> §6    Line: §7if "Communauté Epicube" is loaded in discord:
>  §r
> [13:09:07] [Server thread/ERROR]: [Skript] §c§lLine 33:§7 (bot.sk)
> §c    Can't understand this event: 'on message receive seen by "Communauté Epicube"'
> §6    Line: §7on message receive seen by "Communauté Epicube":
>  §r
> [13:09:07] [Server thread/ERROR]: [Skript] §c§lLine 46:§7 (bot.sk)
> §c    Can't understand this event: 'on member join guild seen by "Communauté Epicube"'
> §6    Line: §7on member join guild seen by "Communauté Epicube":
>  §r
> [13:09:07] [Server thread/ERROR]: [Skript] §c§lLine 49:§7 (bot.sk)
> §c    Can't understand this event: 'on member left guild seen by "Communauté Epicube"'
> §6    Line: §7on member left guild seen by "Communauté Epicube":
>  §r
> [13:09:07] [Server thread/ERROR]: [Skript] §c§lLine 54:§7 (bot.sk)
> §c    Can't understand this event: 'on guild ready'
> §6    Line: §7on guild ready:
>  §r
> [13:09:07] [Server thread/ERROR]: [Skript] §c§lLine 63:§7 (bot.sk)
> §c    Can't understand this event: 'on slash command'
> §6    Line: §7on slash command:
>  §r
> [13:09:07] [Server thread/INFO]: [Skript] Loaded 1 script with a total of 1 trigger and 0 commands in 0.1 seconds
> [13:09:07] [Server thread/INFO]: [Skript] Finished loading.
> >disky debug
> >about DiSky
> [13:09:27] [Server thread/INFO]: DiSky version 4.0-beta2
> [13:09:27] [Server thread/INFO]: The new generation of DiSky, even more powerful and complete!
> [13:09:27] [Server thread/INFO]: Author: ItsTheSky
> >pl
> [13:09:29] [Server thread/INFO]: Plugins (2): Skript, DiSky
> ```

Something is wrong with disky, show the logs when disky was loading

**Comment by Vulqa** [comment]
> > > Are you sure DiSky is been loaded here? Do `/disky debug` and send a screenshot here please.
> > 
> > 
> > The command `/disky debug` returns nothing
> > ```
> > [13:09:07] [Server thread/ERROR]: [Skript] §c§lLine 28:§7 (bot.sk)
> > §c    Can't compare a text with 'loaded in discord'
> > §6    Line: §7if "Communauté Epicube" is loaded in discord:
> >  §r
> > [13:09:07] [Server thread/ERROR]: [Skript] §c§lLine 33:§7 (bot.sk)
> > §c    Can't understand this event: 'on message receive seen by "Communauté Epicube"'
> > §6    Line: §7on message receive seen by "Communauté Epicube":
> >  §r
> > [13:09:07] [Server thread/ERROR]: [Skript] §c§lLine 46:§7 (bot.sk)
> > §c    Can't understand this event: 'on member join guild seen by "Communauté Epicube"'
> > §6    Line: §7on member join guild seen by "Communauté Epicube":
> >  §r
> > [13:09:07] [Server thread/ERROR]: [Skript] §c§lLine 49:§7 (bot.sk)
> > §c    Can't understand this event: 'on member left guild seen by "Communauté Epicube"'
> > §6    Line: §7on member left guild seen by "Communauté Epicube":
> >  §r
> > [13:09:07] [Server thread/ERROR]: [Skript] §c§lLine 54:§7 (bot.sk)
> > §c    Can't understand this event: 'on guild ready'
> > §6    Line: §7on guild ready:
> >  §r
> > [13:09:07] [Server thread/ERROR]: [Skript] §c§lLine 63:§7 (bot.sk)
> > §c    Can't understand this event: 'on slash command'
> > §6    Line: §7on slash command:
> >  §r
> > [13:09:07] [Server thread/INFO]: [Skript] Loaded 1 script with a total of 1 trigger and 0 commands in 0.1 seconds
> > [13:09:07] [Server thread/INFO]: [Skript] Finished loading.
> > >disky debug
> > >about DiSky
> > [13:09:27] [Server thread/INFO]: DiSky version 4.0-beta2
> > [13:09:27] [Server thread/INFO]: The new generation of DiSky, even more powerful and complete!
> > [13:09:27] [Server thread/INFO]: Author: ItsTheSky
> > >pl
> > [13:09:29] [Server thread/INFO]: Plugins (2): Skript, DiSky
> > ```
> 
> Something is wrong with disky, show the logs when disky was loading

```
[14:15:29] [Server thread/INFO]: Starting minecraft server version 1.16.5
[14:15:29] [Server thread/INFO]: Loading properties
[14:15:29] [Server thread/INFO]: This server is running Skigot (Modded Spigot) version git-Spigot-9fb885e-296df56 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)
[14:15:29] [Server thread/INFO]: Debug logging is disabled
[14:15:29] [Server thread/INFO]: Server Ping Player Sample Count: 12
[14:15:29] [Server thread/INFO]: Using 4 threads for Netty based IO
[14:15:29] [Server thread/INFO]: Default game type: SURVIVAL
[14:15:29] [Server thread/INFO]: Generating keypair
[14:15:30] [Server thread/INFO]: Starting Minecraft server on *:25565
[14:15:30] [Server thread/INFO]: Using default channel type
[14:15:31] [Server thread/INFO]: Not loading online / offline mode, since Skigot won't accept any player.
[14:15:31] [Server thread/INFO]: Skigot Done ! For help, type "help"
[14:15:31] [Server thread/INFO]: Debug logging is disabled
[14:15:31] [Server thread/INFO]: Server Ping Player Sample Count: 12
[14:15:31] [Server thread/INFO]: Using 4 threads for Netty based IO
[14:15:31] [Server thread/INFO]: Reloading ResourceManager:
[14:15:31] [Server thread/INFO]: Reloading ResourceManager:
[14:15:33] [Server thread/INFO]: [Skript] Loading Skript v2.6.1
[14:15:33] [Server thread/INFO]: [DiSky] Loading DiSky v4.0-beta2
[14:15:33] [Server thread/INFO]: [Skript] Enabling Skript v2.6.1
[14:15:36] [ForkJoinPool.commonPool-worker-1/INFO]: [Skript] You're currently running the latest stable version of Skript.
[14:15:50] [Server thread/INFO]: [Skript] Loaded 129365 aliases in 16978ms
[14:15:51] [Server thread/INFO]: [Skript]  ~ created by & ® Peter G³ttinger aka Njol ~
[14:15:51] [Server thread/INFO]: [DiSky] Enabling DiSky v4.0-beta2
[14:15:51] [Server thread/ERROR]: Error occurred while enabling DiSky v4.0-beta2 (Is it up to date?)
java.lang.NoClassDefFoundError: de/leonhard/storage/Config
        at info.itsthesky.disky.managers.ConfigManager.init(ConfigManager.java:27) ~[?:?]
        at info.itsthesky.disky.managers.ConfigManager.<init>(ConfigManager.java:19) ~[?:?]
        at info.itsthesky.disky.DiSky.onEnable(DiSky.java:44) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[Skigot.jar:git-Spigot-9fb885e-296df56]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:349) ~[Skigot.jar:git-Spigot-9fb885e-296df56]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:480) ~[Skigot.jar:git-Spigot-9fb885e-296df56]
        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugin(CraftServer.java:463) ~[Skigot.jar:git-Spigot-9fb885e-296df56]
        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugins(CraftServer.java:406) ~[Skigot.jar:git-Spigot-9fb885e-296df56]
        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.reload(CraftServer.java:850) ~[Skigot.jar:git-Spigot-9fb885e-296df56]
        at org.bukkit.Bukkit.reload(Bukkit.java:651) ~[Skigot.jar:git-Spigot-9fb885e-296df56]
        at net.minecraft.server.v1_16_R3.DedicatedServer.init(DedicatedServer.java:275) ~[Skigot.jar:git-Spigot-9fb885e-296df56]
        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:872) ~[Skigot.jar:git-Spigot-9fb885e-296df56]
        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$0(MinecraftServer.java:256) ~[Skigot.jar:git-Spigot-9fb885e-296df56]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_331]
Caused by: java.lang.ClassNotFoundException: de.leonhard.storage.Config
        at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:140) ~[Skigot.jar:git-Spigot-9fb885e-296df56]
        at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:99) ~[Skigot.jar:git-Spigot-9fb885e-296df56]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_331]
        ... 14 more
[14:15:51] [Server thread/INFO]: Server permissions file permissions.yml is empty, ignoring it
[14:15:51] [Server thread/INFO]: [Skript] Loading variables...
[14:15:51] [Server thread/INFO]: [Skript] Loaded 0 variables in 0.0 seconds
[14:15:51] [Server thread/ERROR]: [Skript] ºcºlLine 15:º7 (bot.sk)
ºc    Can't understand this event: 'define new bot named "CommunautÚ Epicube"'
º6    Line: º7define new bot named "CommunautÚ Epicube":
 ºr
[14:15:51] [Server thread/ERROR]: [Skript] ºcºlLine 22:º7 (bot.sk)
ºc    Can't understand this event: 'on ready'
º6    Line: º7on ready:
 ºr
[14:15:51] [Server thread/ERROR]: [Skript] ºcºlLine 28:º7 (bot.sk)
ºc    Can't compare a text with 'loaded in discord'
º6    Line: º7if "CommunautÚ Epicube" is loaded in discord:
 ºr
[14:15:51] [Server thread/ERROR]: [Skript] ºcºlLine 33:º7 (bot.sk)
ºc    Can't understand this event: 'on message receive seen by "CommunautÚ Epicube"'
º6    Line: º7on message receive seen by "CommunautÚ Epicube":
 ºr
[14:15:51] [Server thread/ERROR]: [Skript] ºcºlLine 46:º7 (bot.sk)
ºc    Can't understand this event: 'on member join guild seen by "CommunautÚ Epicube"'
º6    Line: º7on member join guild seen by "CommunautÚ Epicube":
 ºr
[14:15:51] [Server thread/ERROR]: [Skript] ºcºlLine 49:º7 (bot.sk)
ºc    Can't understand this event: 'on member left guild seen by "CommunautÚ Epicube"'
º6    Line: º7on member left guild seen by "CommunautÚ Epicube":
 ºr
[14:15:51] [Server thread/ERROR]: [Skript] ºcºlLine 54:º7 (bot.sk)
ºc    Can't understand this event: 'on guild ready'
º6    Line: º7on guild ready:
 ºr
[14:15:51] [Server thread/ERROR]: [Skript] ºcºlLine 63:º7 (bot.sk)
ºc    Can't understand this event: 'on slash command'
º6    Line: º7on slash command:
 ºr
[14:15:51] [Server thread/INFO]: [Skript] Loaded 1 script with a total of 1 trigger and 0 commands in 0.09 seconds
[14:15:51] [Server thread/INFO]: [Skript] Finished loading.
```

**Comment by SkyCraft78** [comment]
The action you used here was wrong (dependencies haven't been compiled, IDK why).
Use the last created one in order to fix that.
