### ISSUE TITLE
[Bug Report] When adding/removing permissions to/from a role it sends an error

### ISSUE THREAD

**Issue by CerialPvP** [DiSkyOrg/DiSky#43]
So, idk if i'm doing something wrong but i found this when i was trying to do permissions stuff:

The code:
```
add (message send) to permissions of ({ticketing.StaffRole::%discord id of event-guild%} parsed as role) in {ticketing.CurrentTicket::Channel::%discord id of event-member%::%discord id of event-guild%}
```

The error:
```
[15:53:16 ERROR]: #!#! Something went horribly wrong with Skript.
[15:53:16 ERROR]: #!#! This issue is NOT your fault! You probably can't fix it yourself, either.
[15:53:16 ERROR]: #!#! It looks like you are using some plugin(s) that alter how Skript works (addons).
[15:53:16 ERROR]: #!#! Here is full list of them:
[15:53:16 ERROR]: #!#! skRayFall v1.9.21 (https://sk.rayfall.net/) skript-reflect v2.2.4-dev (https://github.com/TPGamesNL/skript-reflect) SkriptJSON v1.0.0 DiSky v4.0-beta2 skUtilities v0.9.2 (https://tim740.github.io/) skript-yaml v1.3.2 MundoSK v1.8.5 (https://forums.skunity.com/resources/mundosk.69/) SkQuery v4.1.3 Reqn v1.2.1 SkEmail v1.7 Skar v1.0 Skent v3.1.0 
[15:53:16 ERROR]: #!#! We could not identify which of those are specially related, so this might also be Skript issue.
[15:53:16 ERROR]: #!#! You should try disabling those plugins one by one, trying to find which one causes it.
[15:53:16 ERROR]: #!#! If the error doesn't disappear even after disabling all listed plugins, it is probably Skript issue.
[15:53:16 ERROR]: #!#! In that case, you will be given instruction on how should you report it.
[15:53:16 ERROR]: #!#! On the other hand, if the error disappears when disabling some plugin, report it to author of that plugin.
[15:53:16 ERROR]: #!#! Only if the author tells you to do so, report it to Skript's issue tracker.
[15:53:16 ERROR]: #!#! 
[15:53:16 ERROR]: #!#! Stack trace:
[15:53:16 ERROR]: #!#! java.lang.NullPointerException: Cannot invoke "info.itsthesky.disky.elements.commands.CommandEvent.getJDAEvent()" because "event" is null
[15:53:16 ERROR]: #!#!     at DiSky.4.0-beta2.jar//info.itsthesky.disky.elements.Types.lambda$static$38(Types.java:237)
[15:53:16 ERROR]: #!#!     at DiSky.4.0-beta2.jar//info.itsthesky.disky.api.DiSkyType$1.parse(DiSkyType.java:57)
[15:53:16 ERROR]: #!#!     at Skript.jar//ch.njol.skript.expressions.ExprParse.get(ExprParse.java:157)
[15:53:16 ERROR]: #!#!     at Skript.jar//ch.njol.skript.lang.util.SimpleExpression.getArray(SimpleExpression.java:99)
[15:53:16 ERROR]: #!#!     at Skript.jar//ch.njol.skript.lang.util.SimpleExpression.getSingle(SimpleExpression.java:57)
[15:53:16 ERROR]: #!#!     at DiSky.4.0-beta2.jar//info.itsthesky.disky.api.skript.EasyElement.parseSingle(EasyElement.java:46)
[15:53:16 ERROR]: #!#!     at DiSky.4.0-beta2.jar//info.itsthesky.disky.elements.properties.PermissionsOf.change(PermissionsOf.java:48)
[15:53:16 ERROR]: #!#!     at Skript.jar//ch.njol.skript.effects.EffChange.execute(EffChange.java:281)
[15:53:16 ERROR]: #!#!     at Skript.jar//ch.njol.skript.lang.Effect.run(Effect.java:51)
[15:53:16 ERROR]: #!#!     at Skript.jar//ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:60)
[15:53:16 ERROR]: #!#!     at Skript.jar//ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:88)
[15:53:16 ERROR]: #!#!     at Skript.jar//ch.njol.skript.effects.Delay$1.run(Delay.java:109)
[15:53:16 ERROR]: #!#!     at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftTask.run(CraftTask.java:101)
[15:53:16 ERROR]: #!#!     at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483)
[15:53:16 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1567)
[15:53:16 ERROR]: #!#!     at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:490)
[15:53:16 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1483)
[15:53:16 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1282)
[15:53:16 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319)
[15:53:16 ERROR]: #!#!     at java.base/java.lang.Thread.run(Thread.java:833)
[15:53:16 ERROR]: #!#! 
[15:53:16 ERROR]: #!#! Version Information:
[15:53:16 ERROR]: #!#!   Skript: 2.6.1 (latest)
[15:53:16 ERROR]: #!#!     Flavor: skriptlang-github
[15:53:16 ERROR]: #!#!     Date: 22:18:42.554713200
[15:53:16 ERROR]: #!#!   Bukkit: 1.17.1-R0.1-SNAPSHOT
[15:53:16 ERROR]: #!#!   Minecraft: 1.17.1
[15:53:16 ERROR]: #!#!   Java: 17.0.3 (OpenJDK 64-Bit Server VM 17.0.3+7-Ubuntu-0ubuntu0.20.04.1)
[15:53:16 ERROR]: #!#!   OS: Linux amd64 5.4.0-110-generic
[15:53:16 ERROR]: #!#! 
[15:53:16 ERROR]: #!#! Server platform: Paper
[15:53:16 ERROR]: #!#! 
[15:53:16 ERROR]: #!#! Current node: null
[15:53:16 ERROR]: #!#! Current item: remove [[permission:message send]] from permissions of {ticketing.OpenedTicket::%{ticketing.CurrentTicket::Num::%the discord id of event-types.member%::%the discord id of event-types.guild%} (as java.lang.Object)%} (as java.lang.String) parsed as a types.member in {ticketing.CurrentTicket::Channel::%the discord id of event-types.member%::%the discord id of event-types.guild%} (as net.dv8tion.jda.api.entities.Channel)
[15:53:16 ERROR]: #!#! Current trigger: button click (on button click:) (distune_ticketing.sk, line 184)
[15:53:16 ERROR]: #!#! 
[15:53:16 ERROR]: #!#! Thread: Server thread
[15:53:16 ERROR]: #!#! 
[15:53:16 ERROR]: #!#! Language: english
[15:53:16 ERROR]: #!#! Link parse mode: DISABLED
[15:53:16 ERROR]: #!#! 
[15:53:16 ERROR]: #!#! End of Error.
[15:53:16 ERROR]: #!#! 
```

**Comment by SkyCraft78** [comment]
Are you in a command scope (like a `discord command` event)?
If not, you'll have to specify the guild for all of the effects & expressions.
I'll add a null-checker anyways, to avoid this sort of exception, but still, your code will simply do nothing because one of the variables won't be set.

**Comment by SkyCraft78** [comment]
Added a null checker

**Comment by CerialPvP** [comment]
> Are you in a command scope (like a `discord command` event)? If not, you'll have to specify the guild for all of the effects & expressions. I'll add a null-checker anyways, to avoid this sort of exception, but still, your code will simply do nothing because one of the variables won't be set.

No I am using it in a slash command event
