### ISSUE TITLE
Error on loading DiSky

### ISSUE THREAD

**Issue by Vulqa** [DiSkyOrg/DiSky#47]
**Server version:** paper 1.18.2
**DiSky version:** disky.4-0-beta4
**Skript version:** 2.6.2

No others plugins and blank server, no scripts
```
Starting org.bukkit.craftbukkit.Main
System Info: Java 17 (Java HotSpot(TM) 64-Bit Server VM 17.0.2+8-LTS-86) Host: Windows 10 10.0 (amd64)
Loading libraries, please wait...
[06:38:24 INFO]: Environment: authHost='https://authserver.mojang.com', accountsHost='https://api.mojang.com', sessionHost='https://sessionserver.mojang.com', servicesHost='https://api.minecraftservices.com', name='PROD'
[06:38:24 INFO]: Found new data pack file/bukkit, loading it automatically
[06:38:26 INFO]: Loaded 7 recipes
[06:38:27 INFO]: Starting minecraft server version 1.18.2
[06:38:27 INFO]: Loading properties
[06:38:27 INFO]: This server is running Paper version git-Paper-341 (MC: 1.18.2) (Implementing API version 1.18.2-R0.1-SNAPSHOT) (Git: fc1752f)
[06:38:27 INFO]: Server Ping Player Sample Count: 12
[06:38:27 INFO]: Using 4 threads for Netty based IO
[06:38:27 INFO]: Default game type: SURVIVAL
[06:38:27 INFO]: Generating keypair
[06:38:27 INFO]: Starting Minecraft server on *:25565
[06:38:27 INFO]: Using default channel type
[06:38:27 INFO]: Paper: Using Java 11 compression from Velocity.
[06:38:27 INFO]: Paper: Using Java cipher from Velocity.
[06:38:28 INFO]: [Skript] Loading Skript v2.6.2
[06:38:28 INFO]: [DiSky] Loading DiSky v4.0-beta2
[06:38:28 INFO]: Server permissions file permissions.yml is empty, ignoring it
[06:38:28 INFO]: Preparing level "world"
[06:38:36 INFO]: Preparing start region for dimension minecraft:overworld
[06:38:37 INFO]: Preparing spawn area: 0%
[06:38:37 INFO]: Preparing spawn area: 0%
[06:38:37 INFO]: Time elapsed: 618 ms
[06:38:37 INFO]: Preparing start region for dimension minecraft:the_nether
[06:38:37 INFO]: Time elapsed: 354 ms
[06:38:37 INFO]: Preparing start region for dimension minecraft:the_end
[06:38:38 INFO]: Time elapsed: 189 ms
[06:38:38 INFO]: [Skript] Enabling Skript v2.6.2
[06:38:38 INFO]: [Skript] Successfully generated the config and the example scripts.
[06:38:38 INFO]: [Skript] You're currently running the latest stable version of Skript.
[06:38:42 INFO]: [Skript] Loaded 143135 aliases in 4359ms
[06:38:43 INFO]: [Skript]  ~ created by & © Peter Güttinger aka Njol ~
[06:38:43 INFO]: [DiSky] Enabling DiSky v4.0-beta2
[06:38:43 ERROR]: Error occurred while enabling DiSky v4.0-beta2 (Is it up to date?)
java.lang.NoClassDefFoundError: de/leonhard/storage/Config
        at info.itsthesky.disky.managers.ConfigManager.init(ConfigManager.java:27) ~[disky-4.0-beta2.jar:?]
        at info.itsthesky.disky.managers.ConfigManager.<init>(ConfigManager.java:19) ~[disky-4.0-beta2.jar:?]
        at info.itsthesky.disky.DiSky.onEnable(DiSky.java:44) ~[disky-4.0-beta2.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:541) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_18_R2.CraftServer.enablePlugin(CraftServer.java:560) ~[paper-1.18.2.jar:git-Paper-341]
        at org.bukkit.craftbukkit.v1_18_R2.CraftServer.enablePlugins(CraftServer.java:474) ~[paper-1.18.2.jar:git-Paper-341]
        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:664) ~[paper-1.18.2.jar:git-Paper-341]
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:431) ~[paper-1.18.2.jar:git-Paper-341]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:316) ~[paper-1.18.2.jar:git-Paper-341]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1163) ~[paper-1.18.2.jar:git-Paper-341]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:315) ~[paper-1.18.2.jar:git-Paper-341]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.ClassNotFoundException: de.leonhard.storage.Config
        at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:151) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:103) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
        ... 14 more
[06:38:43 INFO]: [DiSky] Disabling DiSky v4.0-beta2
[06:38:43 INFO]: Running delayed init tasks
[06:38:43 INFO]: [Skript] Loading variables...
[06:38:43 INFO]: [Skript] Loaded 0 variables in 0.0 seconds
[06:38:43 INFO]: [Skript] All scripts loaded without errors.
[06:38:43 INFO]: [Skript] No scripts were found, maybe you should write some ;)
[06:38:43 INFO]: [Skript] Finished loading.
[06:38:43 INFO]: Done (15.993s)! For help, type "help"
[06:38:43 INFO]: Timings Reset
```

**Comment by SkyCraft78** [comment]
This has already been fixed. Check out the latest action please.
