### ISSUE TITLE
Error skript not loaded

### ISSUE THREAD

**Issue by pzpzn** [DiSkyOrg/DiSky#69]
`[09:43:31] [Server thread/ERROR]: #!#! Something went horribly wrong with Skript.
[09:43:31] [Server thread/ERROR]: #!#! This issue is NOT your fault! You probably can't fix it yourself, either.
[09:43:31] [Server thread/ERROR]: #!#! It looks like you are using some plugin(s) that alter how Skript works (addons).
[09:43:31] [Server thread/ERROR]: #!#! Here is full list of them:
[09:43:31] [Server thread/ERROR]: #!#! DiSky v4.1.1
[09:43:31] [Server thread/ERROR]: #!#! We could not identify which of those are specially related, so this might also be Skript issue.
[09:43:31] [Server thread/ERROR]: #!#! You should try disabling those plugins one by one, trying to find which one causes it.
[09:43:31] [Server thread/ERROR]: #!#! If the error doesn't disappear even after disabling all listed plugins, it is probably Skript issue.
[09:43:31] [Server thread/ERROR]: #!#! In that case, you will be given instruction on how should you report it.
[09:43:31] [Server thread/ERROR]: #!#! On the other hand, if the error disappears when disabling some plugin, report it to author of that plugin.
[09:43:31] [Server thread/ERROR]: #!#! Only if the author tells you to do so, report it to Skript's issue tracker.
[09:43:31] [Server thread/ERROR]: #!#!
[09:43:31] [Server thread/ERROR]: #!#! Stack trace:
[09:43:31] [Server thread/ERROR]: #!#! java.lang.RuntimeException: pattern compiling exception, element class: info.itsthesky.lavaplayer.elements.effects.ConnectBot
[09:43:31] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:226)
[09:43:31] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:177)
[09:43:31] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.Statement.parse(Statement.java:60)
[09:43:31] [Server thread/ERROR]: #!#!     at ch.njol.skript.ScriptLoader.loadItems(ScriptLoader.java:1114)
[09:43:31] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.Section.loadCode(Section.java:90)
[09:43:31] [Server thread/ERROR]: #!#!     at ch.njol.skript.sections.SecConditional.init(SecConditional.java:118)
[09:43:31] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.Section.init(Section.java:69)
[09:43:31] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:255)
[09:43:31] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:177)
[09:43:31] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.Section.lambda$parse$0(Section.java:157)
[09:43:31] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.Section$SectionContext.modify(Section.java:190)
[09:43:31] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.Section.parse(Section.java:156)
[09:43:31] [Server thread/ERROR]: #!#!     at ch.njol.skript.ScriptLoader.loadItems(ScriptLoader.java:1128)
[09:43:31] [Server thread/ERROR]: #!#!     at ch.njol.skript.ScriptLoader.loadScript(ScriptLoader.java:753)
[09:43:31] [Server thread/ERROR]: #!#!     at ch.njol.skript.ScriptLoader.lambda$loadScripts$4(ScriptLoader.java:526)
[09:43:31] [Server thread/ERROR]: #!#!     at ch.njol.skript.ScriptLoader.lambda$makeFuture$2(ScriptLoader.java:418)
[09:43:31] [Server thread/ERROR]: #!#!     at ch.njol.skript.ScriptLoader.makeFuture(ScriptLoader.java:434)
[09:43:31] [Server thread/ERROR]: #!#!     at ch.njol.skript.ScriptLoader.loadScripts(ScriptLoader.java:525)
[09:43:31] [Server thread/ERROR]: #!#!     at ch.njol.skript.ScriptLoader.loadScripts(ScriptLoader.java:469)
[09:43:31] [Server thread/ERROR]: #!#!     at ch.njol.skript.Skript$1.run(Skript.java:786)
[09:43:31] [Server thread/ERROR]: #!#!     at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftTask.run(CraftTask.java:82)
[09:43:31] [Server thread/ERROR]: #!#!     at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:415)
[09:43:31] [Server thread/ERROR]: #!#!     at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1269)
[09:43:31] [Server thread/ERROR]: #!#!     at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:438)
[09:43:31] [Server thread/ERROR]: #!#!     at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1217)
[09:43:31] [Server thread/ERROR]: #!#!     at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1050)
[09:43:31] [Server thread/ERROR]: #!#!     at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:305)
[09:43:31] [Server thread/ERROR]: #!#!     at java.base/java.lang.Thread.run(Thread.java:833)
[09:43:31] [Server thread/ERROR]: #!#! Caused by: ch.njol.skript.patterns.MalformedPatternException: caught exception while compiling pattern [pattern: connect [the] [bot] (in|to) [to] [the] [audio] [channel] %audiochannel%]
[09:43:31] [Server thread/ERROR]: #!#!     at ch.njol.skript.patterns.PatternCompiler.compile(PatternCompiler.java:54)
[09:43:31] [Server thread/ERROR]: #!#!     at java.base/java.util.HashMap.computeIfAbsent(HashMap.java:1220)
[09:43:31] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parse_i(SkriptParser.java:1254)
[09:43:31] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:224)
[09:43:31] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:177)
[09:43:31] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.Statement.parse(Statement.java:60)
[09:43:31] [Server thread/ERROR]: #!#!     at ch.njol.skript.ScriptLoader.loadItems(ScriptLoader.java:1114)
[09:43:31] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.Section.loadCode(Section.java:90)
[09:43:31] [Server thread/ERROR]: #!#!     at ch.njol.skript.sections.SecConditional.init(SecConditional.java:118)
[09:43:31] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.Section.init(Section.java:69)
[09:43:31] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:255)
[09:43:31] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:177)
[09:43:31] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.Section.lambda$parse$0(Section.java:157)
[09:43:31] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.Section$SectionContext.modify(Section.java:190)
[09:43:31] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.Section.parse(Section.java:156)
[09:43:31] [Server thread/ERROR]: #!#!     at ch.njol.skript.ScriptLoader.loadItems(ScriptLoader.java:1128)
[09:43:31] [Server thread/ERROR]: #!#!     at ch.njol.skript.ScriptLoader.loadScript(ScriptLoader.java:753)
[09:43:31] [Server thread/ERROR]: #!#!     at ch.njol.skript.ScriptLoader.lambda$loadScripts$4(ScriptLoader.java:526)
[09:43:31] [Server thread/ERROR]: #!#!     at ch.njol.skript.ScriptLoader.lambda$makeFuture$2(ScriptLoader.java:418)
[09:43:31] [Server thread/ERROR]: #!#!     at ch.njol.skript.ScriptLoader.makeFuture(ScriptLoader.java:434)
[09:43:31] [Server thread/ERROR]: #!#!     at ch.njol.skript.ScriptLoader.loadScripts(ScriptLoader.java:525)
[09:43:31] [Server thread/ERROR]: #!#!     at ch.njol.skript.ScriptLoader.loadScripts(ScriptLoader.java:469)
[09:43:31] [Server thread/ERROR]: #!#!     at ch.njol.skript.Skript$1.run(Skript.java:786)
[09:43:31] [Server thread/ERROR]: #!#!     at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftTask.run(CraftTask.java:82)
[09:43:31] [Server thread/ERROR]: #!#!     at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:415)
[09:43:31] [Server thread/ERROR]: #!#!     at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1269)
[09:43:31] [Server thread/ERROR]: #!#!     at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:438)
[09:43:31] [Server thread/ERROR]: #!#!     at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1217)
[09:43:31] [Server thread/ERROR]: #!#!     at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1050)
[09:43:31] [Server thread/ERROR]: #!#!     at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:305)
[09:43:31] [Server thread/ERROR]: #!#!     at java.base/java.lang.Thread.run(Thread.java:833)
[09:43:31] [Server thread/ERROR]: #!#! Caused by: ch.njol.skript.SkriptAPIException: No class info found for audiochannel
[09:43:31] [Server thread/ERROR]: #!#!     at ch.njol.skript.registrations.Classes.getClassInfo(Classes.java:264)
[09:43:31] [Server thread/ERROR]: #!#!     at ch.njol.skript.patterns.TypePatternElement.fromString(TypePatternElement.java:92)
[09:43:31] [Server thread/ERROR]: #!#!     at ch.njol.skript.patterns.PatternCompiler.compile(PatternCompiler.java:138)
[09:43:31] [Server thread/ERROR]: #!#!     at ch.njol.skript.patterns.PatternCompiler.compile(PatternCompiler.java:49)
[09:43:31] [Server thread/ERROR]: #!#!     at java.base/java.util.HashMap.computeIfAbsent(HashMap.java:1220)
[09:43:31] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parse_i(SkriptParser.java:1254)
[09:43:31] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:224)
[09:43:31] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:177)
[09:43:31] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.Statement.parse(Statement.java:60)
[09:43:31] [Server thread/ERROR]: #!#!     at ch.njol.skript.ScriptLoader.loadItems(ScriptLoader.java:1114)
[09:43:31] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.Section.loadCode(Section.java:90)
[09:43:31] [Server thread/ERROR]: #!#!     at ch.njol.skript.sections.SecConditional.init(SecConditional.java:118)
[09:43:31] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.Section.init(Section.java:69)
[09:43:31] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:255)
[09:43:31] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:177)
[09:43:31] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.Section.lambda$parse$0(Section.java:157)
[09:43:31] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.Section$SectionContext.modify(Section.java:190)
[09:43:31] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.Section.parse(Section.java:156)
[09:43:31] [Server thread/ERROR]: #!#!     at ch.njol.skript.ScriptLoader.loadItems(ScriptLoader.java:1128)
[09:43:31] [Server thread/ERROR]: #!#!     at ch.njol.skript.ScriptLoader.loadScript(ScriptLoader.java:753)
[09:43:31] [Server thread/ERROR]: #!#!     at ch.njol.skript.ScriptLoader.lambda$loadScripts$4(ScriptLoader.java:526)
[09:43:31] [Server thread/ERROR]: #!#!     at ch.njol.skript.ScriptLoader.lambda$makeFuture$2(ScriptLoader.java:418)
[09:43:31] [Server thread/ERROR]: #!#!     at ch.njol.skript.ScriptLoader.makeFuture(ScriptLoader.java:434)
[09:43:31] [Server thread/ERROR]: #!#!     at ch.njol.skript.ScriptLoader.loadScripts(ScriptLoader.java:525)
[09:43:31] [Server thread/ERROR]: #!#!     at ch.njol.skript.ScriptLoader.loadScripts(ScriptLoader.java:469)
[09:43:31] [Server thread/ERROR]: #!#!     at ch.njol.skript.Skript$1.run(Skript.java:786)
[09:43:31] [Server thread/ERROR]: #!#!     at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftTask.run(CraftTask.java:82)
[09:43:31] [Server thread/ERROR]: #!#!     at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:415)
[09:43:31] [Server thread/ERROR]: #!#!     at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1269)
[09:43:31] [Server thread/ERROR]: #!#!     at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:438)
[09:43:31] [Server thread/ERROR]: #!#!     at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1217)
[09:43:31] [Server thread/ERROR]: #!#!     at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1050)
[09:43:31] [Server thread/ERROR]: #!#!     at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:305)
[09:43:31] [Server thread/ERROR]: #!#!     at java.base/java.lang.Thread.run(Thread.java:833)
[09:43:31] [Server thread/ERROR]: #!#!
[09:43:31] [Server thread/ERROR]: #!#! Version Information:
[09:43:31] [Server thread/ERROR]: #!#!   Skript: 2.6.3 (latest)
[09:43:31] [Server thread/ERROR]: #!#!     Flavor: skriptlang-github
[09:43:31] [Server thread/ERROR]: #!#!     Date: 00:55:22.847925631
[09:43:31] [Server thread/ERROR]: #!#!   Bukkit: 1.17.1-R0.1-SNAPSHOT
[09:43:31] [Server thread/ERROR]: #!#!   Minecraft: 1.17.1
[09:43:31] [Server thread/ERROR]: #!#!   Java: 17.0.2 (OpenJDK 64-Bit Server VM 17.0.2+8)
[09:43:31] [Server thread/ERROR]: #!#!   OS: Windows 11 amd64 10.0
[09:43:31] [Server thread/ERROR]: #!#!
[09:43:31] [Server thread/ERROR]: #!#! Server platform: Spigot
[09:43:31] [Server thread/ERROR]: #!#!
[09:43:31] [Server thread/ERROR]: #!#! Current node: make player run cmd "cp template" as op (swiftmenu.sk, line 4)
[09:43:31] [Server thread/ERROR]: #!#! Current item: null
[09:43:31] [Server thread/ERROR]: #!#!
[09:43:31] [Server thread/ERROR]: #!#! Thread: Server thread
[09:43:31] [Server thread/ERROR]: #!#!
[09:43:31] [Server thread/ERROR]: #!#! Language: japanese
[09:43:31] [Server thread/ERROR]: #!#! Link parse mode: DISABLED
[09:43:31] [Server thread/ERROR]: #!#!
[09:43:31] [Server thread/ERROR]: #!#! End of Error.`

**Comment by xXxheatxXx** [comment]
Disabling only disky seems to eliminate the error.

**Comment by SkyCraft78** [comment]
Can you format your code better, please? it's unreadable currently.

**Comment by SkyCraft78** [comment]
Closed for inactivity/no answer.
Feel free to re-open an issue with all the required informations.
