### ISSUE TITLE
Unknown Bug

### ISSUE THREAD

**Issue by BoxPvP** [DiSkyOrg/DiSky#76]
```
[09:47:36 ERROR]: [net.dv8tion.jda.internal.requests.WebSocketClient] Got an unexpected error. Please redirect the following message to the devs:
        JDA 5.0.0-alpha.13_0e17a16
        CHANNEL_UPDATE -> {"nsfw":false,"rate_limit_per_user":0,"flags":0,"bitrate":64000,"user_limit":0,"type":2,"guild_hashes":{"metadata":{"hash":"YlMnMw"},"channels":{"hash":"sH96GQ"},"roles":{"hash":"pxMA+Q"},"version":1},"rtc_region":null,"permission_overwrites":[{"allow":"1024","deny":"1050624","id":"889488491736596560","type":0},{"allow":"0","deny":"2097152","id":"889488491736596561","type":0},{"allow":"1068048","deny":"0","id":"458276816071950337","type":1}],"last_message_id":null,"parent_id":"889491392567599194","name":"members-3301","hashes":{"metadata":{"hash":"YlMnMw"},"channels":{"hash":"sH96GQ"},"roles":{"hash":"pxMA+Q"},"version":1},"guild_id":"889488491736596560","position":3,"id":"889491399601455164"}
java.lang.ClassCastException: class net.dv8tion.jda.internal.entities.VoiceChannelImpl cannot be cast to class net.dv8tion.jda.api.entities.IThreadContainer (net.dv8tion.jda.internal.entities.VoiceChannelImpl and net.dv8tion.jda.api.entities.IThreadContainer are in unnamed module of loader 'DiSky.4.3.0 (1).jar' @72520d0f)
        at net.dv8tion.jda.internal.handle.ChannelUpdateHandler.handleInternally(ChannelUpdateHandler.java:380) ~[DiSky.4.3.0 (1).jar:?]
        at net.dv8tion.jda.internal.handle.SocketHandler.handle(SocketHandler.java:39) ~[DiSky.4.3.0 (1).jar:?]
        at net.dv8tion.jda.internal.requests.WebSocketClient.onDispatch(WebSocketClient.java:953) ~[DiSky.4.3.0 (1).jar:?]
        at net.dv8tion.jda.internal.requests.WebSocketClient.onEvent(WebSocketClient.java:840) ~[DiSky.4.3.0 (1).jar:?]
        at net.dv8tion.jda.internal.requests.WebSocketClient.handleEvent(WebSocketClient.java:818) ~[DiSky.4.3.0 (1).jar:?]
        at net.dv8tion.jda.internal.requests.WebSocketClient.onTextMessage(WebSocketClient.java:979) ~[DiSky.4.3.0 (1).jar:?]
        at com.neovisionaries.ws.client.ListenerManager.callOnTextMessage(ListenerManager.java:369) ~[DiSky.4.3.0 (1).jar:?]
        at com.neovisionaries.ws.client.ReadingThread.callOnTextMessage(ReadingThread.java:233) ~[DiSky.4.3.0 (1).jar:?]
        at com.neovisionaries.ws.client.ReadingThread.handleTextFrame(ReadingThread.java:969) ~[DiSky.4.3.0 (1).jar:?]
        at com.neovisionaries.ws.client.ReadingThread.handleFrame(ReadingThread.java:752) ~[DiSky.4.3.0 (1).jar:?]
        at com.neovisionaries.ws.client.ReadingThread.main(ReadingThread.java:108) ~[DiSky.4.3.0 (1).jar:?]
        at com.neovisionaries.ws.client.ReadingThread.runMain(ReadingThread.java:64) ~[DiSky.4.3.0 (1).jar:?]
        at com.neovisionaries.ws.client.WebSocketThread.run(WebSocketThread.java:45) ~[DiSky.4.3.0 (1).jar:?]
```

**Comment by SkyCraft78** [comment]
Has been fixed in the new JDA version.
