### ISSUE TITLE
Unable to create the configuration file & Problem with the Emoji Library

### ISSUE THREAD

**Issue by Shykuzo** [DiSkyOrg/DiSky#77]
Hello,

Everything is in the title, DiSky could not create the configuration file and the emoji library could not load ...

**Informations :**
    - Minecraft : 1.16.5
    - Skript : 2.6.3
    - DiSky : 4.3.0

**~----------------------------------------~**

```
[14:50:03 INFO]: [DiSky] Enabling DiSky v4.3.0
[14:50:03 ERROR]: [DiSky] Cannot create config file
[14:50:03 WARN]: java.nio.file.NoSuchFileException: plugins/DiSky/config.yml
[14:50:03 WARN]:        at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:92)
[14:50:03 WARN]:        at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:106)
[14:50:03 WARN]:        at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111)
[14:50:03 WARN]:        at java.base/sun.nio.fs.UnixFileSystemProvider.newByteChannel(UnixFileSystemProvider.java:219)
[14:50:03 WARN]:        at java.base/java.nio.file.spi.FileSystemProvider.newOutputStream(FileSystemProvider.java:478)
[14:50:03 WARN]:        at java.base/java.nio.file.Files.newOutputStream(Files.java:224)
[14:50:03 WARN]:        at java.base/java.nio.file.Files.write(Files.java:3491)
[14:50:03 WARN]:        at info.itsthesky.disky.DiSky.onEnable(DiSky.java:66)
[14:50:03 WARN]:        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263)
[14:50:03 WARN]:        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370)
[14:50:03 WARN]:        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:500)
[14:50:03 WARN]:        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugin(CraftServer.java:518)
[14:50:03 WARN]:        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugins(CraftServer.java:432)
[14:50:03 WARN]:        at net.minecraft.server.v1_16_R3.MinecraftServer.loadWorld(MinecraftServer.java:599)
[14:50:03 WARN]:        at net.minecraft.server.v1_16_R3.DedicatedServer.init(DedicatedServer.java:298)
[14:50:03 WARN]:        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1074)
[14:50:03 WARN]:        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:291)
[14:50:03 WARN]:        at java.base/java.lang.Thread.run(Thread.java:831)
[14:50:03 ERROR]: Cannot load plugins/DiSky/config.yml
java.io.FileNotFoundException: plugins/DiSky/config.yml (No such file or directory)
        at java.io.FileInputStream.open0(Native Method) ~[?:?]
        at java.io.FileInputStream.open(FileInputStream.java:211) ~[?:?]
        at java.io.FileInputStream.<init>(FileInputStream.java:153) ~[?:?]
        at org.bukkit.configuration.file.FileConfiguration.load(FileConfiguration.java:126) ~[patched_1.16.5.jar:git-Paper-794]
        at info.itsthesky.disky.managers.Configuration.loadConfiguration(Configuration.java:38) ~[?:?]
        at info.itsthesky.disky.DiSky.onEnable(DiSky.java:72) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[patched_1.16.5.jar:git-Paper-794]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370) ~[patched_1.16.5.jar:git-Paper-794]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:500) ~[patched_1.16.5.jar:git-Paper-794]
        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugin(CraftServer.java:518) ~[patched_1.16.5.jar:git-Paper-794]
        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugins(CraftServer.java:432) ~[patched_1.16.5.jar:git-Paper-794]
        at net.minecraft.server.v1_16_R3.MinecraftServer.loadWorld(MinecraftServer.java:599) ~[patched_1.16.5.jar:git-Paper-794]
        at net.minecraft.server.v1_16_R3.DedicatedServer.init(DedicatedServer.java:298) ~[patched_1.16.5.jar:git-Paper-794]
        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1074) ~[patched_1.16.5.jar:git-Paper-794]
        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:291) ~[patched_1.16.5.jar:git-Paper-794]
        at java.lang.Thread.run(Thread.java:831) [?:?]
[14:50:03 INFO]: [DiSky] Saving emoji's file ...
[14:50:03 WARN]: java.nio.file.NoSuchFileException: plugins/DiSky/emojis.json
[14:50:03 WARN]:        at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:92)
[14:50:03 WARN]:        at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:106)
[14:50:03 WARN]:        at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111)
[14:50:03 WARN]:        at java.base/sun.nio.fs.UnixFileSystemProvider.newByteChannel(UnixFileSystemProvider.java:219)
[14:50:03 WARN]:        at java.base/java.nio.file.spi.FileSystemProvider.newOutputStream(FileSystemProvider.java:478)
[14:50:03 WARN]:        at java.base/java.nio.file.Files.newOutputStream(Files.java:224)
[14:50:03 WARN]:        at java.base/java.nio.file.Files.write(Files.java:3491)
[14:50:03 WARN]:        at info.itsthesky.disky.DiSky.onEnable(DiSky.java:88)
[14:50:03 WARN]:        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263)
[14:50:03 WARN]:        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370)
[14:50:03 WARN]:        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:500)
[14:50:03 WARN]:        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugin(CraftServer.java:518)
[14:50:03 WARN]:        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugins(CraftServer.java:432)
[14:50:03 WARN]:        at net.minecraft.server.v1_16_R3.MinecraftServer.loadWorld(MinecraftServer.java:599)
[14:50:03 WARN]:        at net.minecraft.server.v1_16_R3.DedicatedServer.init(DedicatedServer.java:298)
[14:50:03 WARN]:        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1074)
[14:50:03 WARN]:        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:291)
[14:50:03 WARN]:        at java.base/java.lang.Thread.run(Thread.java:831)
[14:50:03 ERROR]: [DiSky] An error occurred while saving emojis file! Emojis will not be available.
[14:50:03 INFO]: [DiSky] Success!
[14:50:03 INFO]: [DiSky] Loading emoji library ...
[14:50:03 WARN]: java.io.FileNotFoundException: plugins/DiSky/emojis.json (No such file or directory)
[14:50:03 WARN]:        at java.base/java.io.FileInputStream.open0(Native Method)
[14:50:03 WARN]:        at java.base/java.io.FileInputStream.open(FileInputStream.java:211)
[14:50:03 WARN]:        at java.base/java.io.FileInputStream.<init>(FileInputStream.java:153)
[14:50:03 WARN]:        at info.itsthesky.disky.api.emojis.EmojiStore.loadLocal(EmojiStore.java:24)
[14:50:03 WARN]:        at info.itsthesky.disky.DiSky.onEnable(DiSky.java:97)
[14:50:03 WARN]:        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263)
[14:50:03 WARN]:        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370)
[14:50:03 WARN]:        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:500)
[14:50:03 WARN]:        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugin(CraftServer.java:518)
[14:50:03 WARN]:        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugins(CraftServer.java:432)
[14:50:03 WARN]:        at net.minecraft.server.v1_16_R3.MinecraftServer.loadWorld(MinecraftServer.java:599)
[14:50:03 WARN]:        at net.minecraft.server.v1_16_R3.DedicatedServer.init(DedicatedServer.java:298)
[14:50:03 WARN]:        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1074)
[14:50:03 WARN]:        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:291)
[14:50:03 WARN]:        at java.base/java.lang.Thread.run(Thread.java:831)
[14:50:03 ERROR]: [DiSky] An error occurred while loading emojis! They will not be available.
[14:50:03 INFO]: [DiSky] Success!
```

**Comment by Shykuzo** [comment]
The problem was fixed after restarting the server ^^
