### ISSUE TITLE
Unexpected Error

### ISSUE THREAD

**Issue by CerialPvP** [DiSkyOrg/DiSky#78]
Hey, I am getting this error at console but don't know what it means. It didn't appear in previous versions of DiSky so I figured I should report this.
```applescript
[13:21:01 ERROR]: [net.dv8tion.jda.internal.requests.WebSocketClient] Got an unexpected error. Please redirect the following message to the devs:
        JDA 5.0.0-alpha.13_0e17a16
        CHANNEL_UPDATE -> {"nsfw":false,"rate_limit_per_user":0,"flags":0,"bitrate":64000,"user_limit":0,"type":2,"guild_hashes":{"metadata":{"hash":"U04DVw"},"channels":{"hash":"JmlCcg"},"roles":{"hash":"6mep0w"},"version":1},"rtc_region":null,"permission_overwrites":[{"allow":"0","deny":"2048","id":"720285662573625434","type":0},{"allow":"1068048","deny":"0","id":"458276816071950337","type":1},{"allow":"1024","deny":"825233425","id":"718519105644396694","type":0}],"last_message_id":null,"parent_id":"789455875940024351","name":"Member Count: 446","hashes":{"metadata":{"hash":"U04DVw"},"channels":{"hash":"JmlCcg"},"roles":{"hash":"6mep0w"},"version":1},"guild_id":"718519105644396694","position":1,"id":"789455882140123156"}
java.lang.ClassCastException: class net.dv8tion.jda.internal.entities.VoiceChannelImpl cannot be cast to class net.dv8tion.jda.api.entities.IThreadContainer (net.dv8tion.jda.internal.entities.VoiceChannelImpl and net.dv8tion.jda.api.entities.IThreadContainer are in unnamed module of loader 'DiSky.4.3.0.jar' @2289a977)
        at net.dv8tion.jda.internal.handle.ChannelUpdateHandler.handleInternally(ChannelUpdateHandler.java:380) ~[DiSky.4.3.0.jar:?]
        at net.dv8tion.jda.internal.handle.SocketHandler.handle(SocketHandler.java:39) ~[DiSky.4.3.0.jar:?]
        at net.dv8tion.jda.internal.requests.WebSocketClient.onDispatch(WebSocketClient.java:953) ~[DiSky.4.3.0.jar:?]
        at net.dv8tion.jda.internal.requests.WebSocketClient.onEvent(WebSocketClient.java:840) ~[DiSky.4.3.0.jar:?]
        at net.dv8tion.jda.internal.requests.WebSocketClient.handleEvent(WebSocketClient.java:818) ~[DiSky.4.3.0.jar:?]
        at net.dv8tion.jda.internal.requests.WebSocketClient.onTextMessage(WebSocketClient.java:979) ~[DiSky.4.3.0.jar:?]
        at com.neovisionaries.ws.client.ListenerManager.callOnTextMessage(ListenerManager.java:369) ~[DiSky.4.3.0.jar:?]
        at com.neovisionaries.ws.client.ReadingThread.callOnTextMessage(ReadingThread.java:233) ~[DiSky.4.3.0.jar:?]
        at com.neovisionaries.ws.client.ReadingThread.handleTextFrame(ReadingThread.java:969) ~[DiSky.4.3.0.jar:?]
        at com.neovisionaries.ws.client.ReadingThread.handleFrame(ReadingThread.java:752) ~[DiSky.4.3.0.jar:?]
        at com.neovisionaries.ws.client.ReadingThread.main(ReadingThread.java:108) ~[DiSky.4.3.0.jar:?]
        at com.neovisionaries.ws.client.ReadingThread.runMain(ReadingThread.java:64) ~[DiSky.4.3.0.jar:?]
        at com.neovisionaries.ws.client.WebSocketThread.run(WebSocketThread.java:45) ~[DiSky.4.3.0.jar:?]
```

**Comment by SkyCraft78** [comment]
Same as #76
