### ISSUE TITLE
2.5 weird topic null error

### ISSUE THREAD

**Issue by OverBrave** [DiSkyOrg/DiSky#89]
This problem start occur after upgrade disky version to 4.5
```
[22:58:58 ERROR]: #!#! Stack trace:
[22:58:58 ERROR]: #!#! java.lang.NullPointerException: Cannot invoke "net.dv8tion.jda.api.entities.channel.middleman.StandardGuildMessageChannel.getManager()" because "channel" is null
[22:58:58 ERROR]: #!#!     at DiSky.4.5.0.jar//info.itsthesky.disky.elements.properties.channels.ChannelTopic.change(ChannelTopic.java:35)
[22:58:58 ERROR]: #!#!     at DiSky.4.5.0.jar//info.itsthesky.disky.elements.properties.channels.ChannelTopic.change(ChannelTopic.java:13)
[22:58:58 ERROR]: #!#!     at DiSky.4.5.0.jar//info.itsthesky.disky.api.skript.action.ActionProperty.change(ActionProperty.java:29)
[22:58:58 ERROR]: #!#!     at DiSky.4.5.0.jar//info.itsthesky.disky.api.changers.ChangeablePropertyExpression.change(ChangeablePropertyExpression.java:12)
[22:58:58 ERROR]: #!#!     at Skript.jar//ch.njol.skript.effects.EffChange.execute(EffChange.java:282)
[22:58:58 ERROR]: #!#!     at Skript.jar//ch.njol.skript.lang.Effect.run(Effect.java:50)
[22:58:58 ERROR]: #!#!     at Skript.jar//ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:61)
[22:58:58 ERROR]: #!#!     at Skript.jar//ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:89)
[22:58:58 ERROR]: #!#!     at DiSky.4.5.0.jar//info.itsthesky.disky.api.skript.WaiterEffect.lambda$runItems$0(WaiterEffect.java:151)
[22:58:58 ERROR]: #!#!     at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftTask.run(CraftTask.java:101)
[22:58:58 ERROR]: #!#!     at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483)
[22:58:58 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1520)
[22:58:58 ERROR]: #!#!     at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:486)
[22:58:58 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1444)
[22:58:58 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.v(MinecraftServer.java:1214)
[22:58:58 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:310)
[22:58:58 ERROR]: #!#!     at java.base/java.lang.Thread.run(Thread.java:858)
[22:58:58 ERROR]: #!#! 
[22:58:58 ERROR]: #!#! Version Information:
[22:58:58 ERROR]: #!#!   Skript: 2.6.3 (latest)
[22:58:58 ERROR]: #!#!     Flavor: skriptlang-github
[22:58:58 ERROR]: #!#!     Date: 00:55:22.847925631
[22:58:58 ERROR]: #!#!   Bukkit: 1.19.2-R0.1-SNAPSHOT
[22:58:58 ERROR]: #!#!   Minecraft: 1.19.2
[22:58:58 ERROR]: #!#!   Java: 18.0.2 (Eclipse OpenJ9 VM openj9-0.33.1)
[22:58:58 ERROR]: #!#!   OS: Linux amd64 5.15.0-48-generic
[22:58:58 ERROR]: #!#! 
[22:58:58 ERROR]: #!#! Server platform: Paper
[22:58:58 ERROR]: #!#! 
[22:58:58 ERROR]: #!#! Current node: null
[22:58:58 ERROR]: #!#! Current item: set channel topic to "test"
[22:58:58 ERROR]: #!#! Current trigger: quit (simple event) (bot.sk, line 63)
```
`set topic of text channel with id "blabla" to "test"`

**Comment by SkyCraft78** [comment]
It appears that your channel is null.
I'll add a null checker in the next update ,but it don't change anything as you'll receive a different error.
Maybe the ID is wrong ?

**Comment by SkyCraft78** [comment]
It appears that your channel is null.
I'll add a null checker in the next update ,but it don't change anything as you'll receive a different error.
Maybe the ID is wrong ?

**Comment by OverBrave** [comment]
> It appears that your channel is null. I'll add a null checker in the next update ,but it don't change anything as you'll receive a different error. Maybe the ID is wrong ?

I just changed version of Disky, in 4.4.3 version working without problem. And also I checked id of channel, its same.

**Comment by SkyCraft78** [comment]
Again, nothing changed there, and this error can only happen if the input channel is null, aka invalid.
![image](https://user-images.githubusercontent.com/50667548/196242451-1892bdf4-238f-4a4c-a67d-a67b9b88e3f2.png)
Still added a null checker for future cases.
